# Generated by Django 2.2.12 on 2020-06-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-created',), 'verbose_name': '文章', 'verbose_name_plural': '文章列表'},
        ),
        migrations.AlterModelTable(
            name='articlepost',
            table='article',
        ),
    ]
