# Generated by Django 2.2.12 on 2020-07-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200715_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/%Y/m%/%d'),
        ),
    ]
